package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.coolweather.coolweather.db.County;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNTY".
*/
public class CountyDao extends AbstractDao<County, Integer> {

    public static final String TABLENAME = "COUNTY";

    /**
     * Properties of entity County.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", true, "ID");
        public final static Property CountyName = new Property(1, String.class, "countyName", false, "county_name");
        public final static Property CountyCode = new Property(2, int.class, "countyCode", false, "county_code");
        public final static Property WeatherId = new Property(3, String.class, "weatherId", false, "weather_id");
        public final static Property CityId = new Property(4, int.class, "cityId", false, "city_id");
    }


    public CountyDao(DaoConfig config) {
        super(config);
    }
    
    public CountyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNTY\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"county_name\" TEXT," + // 1: countyName
                "\"county_code\" INTEGER NOT NULL ," + // 2: countyCode
                "\"weather_id\" TEXT," + // 3: weatherId
                "\"city_id\" INTEGER NOT NULL );"); // 4: cityId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNTY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, County entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String countyName = entity.getCountyName();
        if (countyName != null) {
            stmt.bindString(2, countyName);
        }
        stmt.bindLong(3, entity.getCountyCode());
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(4, weatherId);
        }
        stmt.bindLong(5, entity.getCityId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, County entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String countyName = entity.getCountyName();
        if (countyName != null) {
            stmt.bindString(2, countyName);
        }
        stmt.bindLong(3, entity.getCountyCode());
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(4, weatherId);
        }
        stmt.bindLong(5, entity.getCityId());
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public County readEntity(Cursor cursor, int offset) {
        County entity = new County( //
            cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // countyName
            cursor.getInt(offset + 2), // countyCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // weatherId
            cursor.getInt(offset + 4) // cityId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, County entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setCountyName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCountyCode(cursor.getInt(offset + 2));
        entity.setWeatherId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCityId(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(County entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(County entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(County entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
